---medicos disponibles en una hora especifica----

SELECT NOMBRE "Medicos Disponibles" FROM MEDICO
MINUS
SELECT NOMBRE FROM
(SELECT CI_MEDICO, FECHA FROM CITA
UNION ALL
SELECT CI_MEDICO, FECHA FROM CITA_TRATAMIENTO)
JOIN
MEDICO
ON(CI_MEDICO=CI)
WHERE FECHA=TO_DATE('&FECHA','DD/MM/YY:HH');

----tratamientos realizados en un dia------

SELECT P.NOMBRE "Paciente", M.NOMBRE "Medico", T.DESCRIPCION "Descripcion"
FROM CITA_TRATAMIENTO CT
JOIN CITA C ON(CT.CITA_ID=C.ID)
JOIN PACIENTE P ON (C.CI_PACIENTE=P.CI) JOIN MEDICO M ON(CT.CI_MEDICO=M.CI)
JOIN TRATAMIENTO T ON(CT.TRATAMIENTO_ID=T.ID)
WHERE CT.FECHA=TO_DATE('&FECHA','DD/MM/YY');


----FUNCION QUE DEVUELVE LAS HORAS DISPONIBLES EN UNA FECHA----
/*
DEVUELVE UNA CADENA CON LAS HORAS SEPARADAS POR '|'
*/

CREATE OR REPLACE FUNCTION HORAS_DISPONIBLES 
(
  V_FECHA IN VARCHAR2 
) RETURN VARCHAR2 AS

  CURSOR C_HORAS IS
  SELECT HORA FROM
  (SELECT TO_CHAR(FECHA,'HH24') HORA, COUNT(*) CANTIDAD FROM
  (SELECT FECHA FROM CITA
  UNION ALL
  SELECT FECHA FROM CITA_TRATAMIENTO)
  GROUP BY TO_CHAR(FECHA,'DD/MM/YY'), TO_CHAR(FECHA,'HH24')
  HAVING TO_CHAR(FECHA,'DD/MM/YY')=V_FECHA)
  WHERE TO_NUMBER(HORA)>7 AND TO_NUMBER(HORA)<17 AND TO_NUMBER(HORA)!=12 AND CANTIDAD=3
  ORDER BY TO_NUMBER(HORA);
  FILA_CURSOR C_HORAS%ROWTYPE;
  RESPUESTA VARCHAR(50):='';

BEGIN
  DBMS_OUTPUT.PUT_LINE('HORAS DISPONIBLES:');
  OPEN C_HORAS;
  FETCH C_HORAS INTO FILA_CURSOR;
  FOR I IN 8..16 LOOP
    IF FILA_CURSOR.HORA = I THEN
      FETCH C_HORAS INTO FILA_CURSOR;
    ELSIF I!=12 THEN
      DBMS_OUTPUT.PUT_LINE(I);
      RESPUESTA:=RESPUESTA||TO_CHAR(I)||'|';
    END IF;
  END LOOP;
  RETURN RESPUESTA;
END HORAS_DISPONIBLES;
