---medicos disponibles en una hora especifica----
SELECT NOMBRE "Medicos Disponibles" FROM MEDICO
MINUS
SELECT NOMBRE FROM(SELECT CI_MEDICO, FECHA FROM CITA
UNION ALL
SELECT CI_MEDICO, FECHA FROM CITA_TRATAMIENTO)
JOIN
MEDICO
ON(CI_MEDICO=CI)
WHERE FECHA=TO_DATE('&FECHA','DD/MM/YY:HH');

----tratamientos realizados en un dia------
SELECT P.NOMBRE "Paciente", M.NOMBRE "Medico", T.DESCRIPCION "Descripcion tratamiento"
FROM CITA_TRATAMIENTO CT
JOIN CITA C ON(CT.CITA_ID=C.ID)
JOIN PACIENTE P ON (C.CI_PACIENTE=P.CI) 
JOIN MEDICO M ON(CT.CI_MEDICO=M.CI)
JOIN TRATAMIENTO T ON(CT.TRATAMIENTO_ID=T.ID)
WHERE CT.FECHA=TO_DATE('&FECHA','DD/MM/YY');

------CITAS DE MEDICO EN UN RANGO-----
SELECT P.NOMBRE, C.FECHA FROM CITA C JOIN PACIENTE P
ON(C.CI_PACIENTE=P.CI)
WHERE C.CI_MEDICO='&CEDULAMEDICO' AND
C.FECHA BETWEEN TO_DATE('&FINI','DD/MM/YY') AND TO_DATE('&FFIN','DD/MM/YY');

------------EL DERROCHADOR-----------------------
SELECT M.NOMBRE "Medico", SUM(TI.CANTIDAD) "Cantidad utilizada" FROM CITA_TRATAMIENTO CT JOIN
TRATAMIENTO_IMPLEMENTO TI ON(CT.CITA_ID=TI.CITA_ID AND CT.TRATAMIENTO_ID=TI.TRATAMIENTO_ID)
JOIN MEDICO M ON(M.CI=CT.CI_MEDICO)
JOIN IMPLEMENTO I ON(I.ID=TI.IMPLEMENTO_ID)
GROUP BY I.ID, M.NOMBRE HAVING (I.ID=&IDIMPLEMENTO) ORDER BY 2;

----------CONSULTAS SENCILLAS-------------------------------

--HISTORIAL DE CITAS
SELECT NOMBRE, FECHA, MOTIVO FROM CITA JOIN PACIENTE ON(CI=CITA.CI_PACIENTE)
WHERE CI_PACIENTE='&CIPACIENTE' ORDER BY FECHA;

--HISTORIAL DE TRATAMIENTOS
SELECT NOMBRE, CT.FECHA, CASE WHEN ABONADO<CT.COSTO THEN 'INSOLVENTE' ELSE 'SOLVENTE' END
FROM CITA_TRATAMIENTO CT JOIN CITA C ON(ID=CITA_ID) JOIN PACIENTE P ON(P.CI=C.CI_PACIENTE)
WHERE C.CI_PACIENTE=&CIPACIENTE ORDER BY CT.FECHA;

--PACIENTES INSOLVENTES CON LOS PAGOS
SELECT NOMBRE, CT.FECHA FECHA, CASE WHEN SYSDATE-CT.FECHA>=30 THEN 'PLAZO TERMINADO' ELSE 'QUEDAN '||TO_CHAR(SYSDATE-CT.FECHA,'99')||' DIA(S)' END PLAZO
FROM CITA_TRATAMIENTO CT JOIN CITA C ON(CT.ID=C.CITA_ID)
JOIN PACIENTE P ON(P.CI=C.CI_PACIENTE) WHERE ABONADO<CT.COSTO;


/**** GANANCIAS GENERALES */
SELECT SUM(NVL2(COSTO,COSTO,0)) AS ESPERADAS, SUM(NVL2(ABONADO,ABONADO,0)) AS OBTENIDAS FROM CITA_TRATAMIENTO

/**** GANANCIAS POR MES */

SELECT
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'01',ABONADO,0)) AS ENERO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'02',ABONADO,0)) AS FEBRERO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'03',ABONADO,0)) AS MARZO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'04',ABONADO,0)) AS ABRIL,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'05',ABONADO,0)) AS MAYO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'06',ABONADO,0)) AS JUNIO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'07',ABONADO,0)) AS JULIO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'08',ABONADO,0)) AS AGOSTO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'09',ABONADO,0)) AS SEPTIEMBRE,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'10',ABONADO,0)) AS OCTUBRE,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'11',ABONADO,0)) AS NOVIEMBRE,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'12',ABONADO,0)) AS DICIEMBRE
FROM CITA_TRATAMIENTO;

------------------------GRAFICAS--------------------------------------------------------------------

---------------------CANTIDAD DE IMPLEMENTOS GASTADOS EN UN MES Y UN AÑO ESPECIFICOS----------------
--------------------DIAGRAMA DE BARRAS---------------------------------------------------------

SELECT I.NOMBRE AS IMPLEMENTO, SUM(TI.CANTIDAD) AS CANTIDAD FROM TRATAMIENTO_IMPLEMENTO TI JOIN CITA_TRATAMIENTO CT
ON (TI.TRATAMIENTO_ID=CT.TRATAMIENTO_ID AND TI.CITA_ID=CT.CITA_ID) JOIN IMPLEMENTO I
ON (TI.IMPLEMENTO_ID=I.ID) WHERE TO_CHAR(FECHA,'MM')='&MM' AND TO_CHAR(FECHA,'YYYY')='&YYYY'
GROUP BY I.NOMBRE;


-------------------- BARRAS: CANTIDAD DE CITAS POR MESES DE UN AÑO DADO -----------------------------

SELECT
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'01',1,0)) AS ENERO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'02',1,0)) AS FEBRERO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'03',1,0)) AS MARZO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'04',1,0)) AS ABRIL,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'05',1,0)) AS MAYO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'06',1,0)) AS JUNIO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'07',1,0)) AS JULIO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'08',1,0)) AS AGOSTO,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'09',1,0)) AS SEPTIEMBRE,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'10',1,0)) AS OCTUBRE,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'11',1,0)) AS NOVIEMBRE,
  SUM(DECODE(TO_CHAR(FECHA,'MM'),'12',1,0)) AS DICIEMBRE
FROM CITA
WHERE TO_CHAR(FECHA,'YYYY') = &anho;

