REM INSERTING into IMPLEMENTOS
SET DEFINE OFF;

Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('1','Nexium','Praesent Luctus Curabitur Corp.','tellus sem mollis dui, in sodales elit erat','90202','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('2','Cyclobenzaprin HCl','Ac Feugiat Foundation','massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede','75617','5');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('3','Amlodipine Besylate','Faucibus PC','fringilla purus mauris a nunc. In at','38287','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('4','Amlodipine Besylate','Quis Pede PC','Aenean gravida nunc','51781','17');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('5','Metoprolol Tartrate ','Eu Lacus Quisque Foundation','sapien imperdiet ornare. In faucibus. Morbi vehicula.','34610','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('6','Advair Diskus','Non Institute','nisi sem semper','76147','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('7','Lisinopril','Justo Corporation','nunc id enim. Curabitur massa. Vestibulum accumsan neque et','51628','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('8','Alendronate Sodium','Nulla Cras Company','ullamcorper viverra.','47870','9');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('9','LevothyroxineSodium','Vel Incorporated','et','73354','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('10','Lisinopril','Diam Pellentesque Institute','Cras pellentesque. Sed dictum. Proin','29369','12');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('11','Metformin HCl','Non Quam Pellentesque LLC','ac arcu. Nunc','5868','10');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('12','Prednisone','Pellentesque Habitant Ltd','ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,','16218','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('13','Ventolin HFA','Ac Corporation','convallis convallis dolor.','40723','9');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('14','Metformin HCl','Nisl Arcu Associates','enim,','8952','17');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('15','Fluoxetine HCl','Tellus Faucibus Industries','a tortor. Nunc commodo','39389','10');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('16','Amlodipine Besylate','Sed Sem Institute','cursus purus. Nullam scelerisque neque sed','92385','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('17','Lorazepam','Ut Dolor Dapibus Incorporated','Sed nulla ante, iaculis nec,','90383','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('18','Fluconazole','Rutrum Eu Ultrices LLC','facilisis lorem tristique aliquet. Phasellus','8561','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('19','Amoxicillin','Ante LLC','magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum','56642','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('20','Cialis','Erat Eget Limited','posuere','95216','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('21','Carvedilol','Vitae Risus Duis Incorporated','laoreet ipsum. Curabitur consequat, lectus sit amet luctus','46305','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('22','Paroxetine HCl','Mauris Quis Turpis Consulting','fermentum','8247','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('23','Alendronate Sodium','Ac Facilisis LLC','nisi sem semper erat, in consectetuer ipsum nunc id','8328','9');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('24','Alprazolam','Nullam Velit Dui Associates','ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere','60503','7');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('25','Famotidine','Sociis Natoque Penatibus Corp.','Proin eget odio. Aliquam vulputate','44646','5');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('26','Lyrica','In Faucibus Orci Consulting','Praesent eu nulla at sem','80193','14');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('27','Vyvanse','Ipsum Industries','magna. Duis dignissim tempor arcu. Vestibulum ut','77529','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('28','Fluoxetine HCl','Aenean Gravida Corporation','molestie orci tincidunt adipiscing. Mauris','93497','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('29','LevothyroxineSodium','Sit Amet Consectetuer Ltd','congue. In scelerisque scelerisque','65141','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('30','Furosemide','Faucibus Morbi LLP','lorem, luctus ut,','98973','7');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('31','Metformin HCl','Mauris Sagittis Placerat Inc.','In faucibus. Morbi vehicula. Pellentesque tincidunt','55535','12');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('32','Metformin HCl','Lobortis Quis Pede Incorporated','eget tincidunt dui augue eu tellus.','84769','14');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('33','Lisinopril','Id Ante PC','Aliquam erat volutpat. Nulla dignissim. Maecenas ornare','52125','16');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('34','Hydrochlorothiazide','Dolor Fusce LLP','facilisi. Sed neque.','19263','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('35','Lipitor','Aliquet Molestie Ltd','facilisis non, bibendum','28986','7');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('36','Metformin HCl','Phasellus Elit Pede Corp.','ornare lectus justo eu arcu. Morbi','49476','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('37','Levothyroxine Sodium','Eros PC','sit amet luctus vulputate, nisi','77285','16');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('38','Omeprazole (Rx)','Netus Et Corporation','lacinia orci, consectetuer euismod est arcu ac orci.','71229','15');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('39','Atenolol','In Scelerisque Corporation','Nulla','39099','16');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('40','Benicar HCT','Imperdiet Ullamcorper PC','diam dictum sapien. Aenean massa. Integer vitae nibh.','38859','16');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('41','Oxycodone/APAP','Neque Pellentesque Massa Industries','vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros','66271','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('42','Carvedilol','Sed Institute','malesuada fames ac turpis egestas. Fusce aliquet magna a neque.','89476','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('43','Digoxin','Magnis Ltd','nisl. Maecenas malesuada fringilla est. Mauris','59246','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('44','Zolpidem Tartrate','Luctus Ut Pellentesque Associates','urna suscipit nonummy. Fusce fermentum fermentum','48688','19');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('45','Vytorin','Mauris Eu Corporation','fringilla purus','39130','19');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('46','Premarin','Nunc Quisque Ornare Ltd','massa. Mauris','77416','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('47','Methylprednisolone','Interdum Curabitur Inc.','non enim.','88003','14');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('48','Metformin HCl','Et Risus Inc.','dictum magna.','14695','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('49','Furosemide','Erat Industries','placerat eget, venenatis a, magna. Lorem ipsum dolor sit','82341','9');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('54','Alprazolam','Phasellus Elit Corporation','risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a','69856','10');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('55','Cialis','Non Lacinia At LLC','tincidunt, nunc ac mattis ornare,','62282','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('56','Nexium','Donec LLP','libero at auctor ullamcorper, nisl arcu iaculis enim, sit','39501','15');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('57','Diovan HCT','Sed LLC','felis purus ac tellus. Suspendisse','21951','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('58','Hydrocodone/APAP','Dolor PC','Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi','34074','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('59','Flovent HFA','Nibh Company','sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum','60551','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('60','Alprazolam','Lacus Ut Corp.','pede, nonummy','18520','15');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('61','Diazepam','Arcu Company','ante','70125','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('62','Simvastatin','Dolor Tempus Non Industries','nisl. Maecenas malesuada fringilla est. Mauris eu turpis.','31432','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('63','Prednisone','Convallis Est LLP','Maecenas mi felis, adipiscing fringilla, porttitor','8078','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('64','Nasonex','Odio Semper LLC','Donec nibh enim,','64027','19');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('65','Clonazepam','Sed Orci Lobortis Associates','eu, odio. Phasellus at augue id ante dictum cursus. Nunc','74230','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('66','Cialis','Fusce Dolor Industries','libero et tristique','87964','17');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('67','Hydrocodone/APAP','Ut Foundation','volutpat. Nulla dignissim.','50487','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('68','Sulfamethoxazole/Trimethoprim','In Industries','dictum augue malesuada malesuada. Integer id magna et ipsum cursus','45434','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('69','TriNessa','Tempor Diam Dictum Industries','dui. Fusce aliquam,','39082','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('70','Hydrocodone/APAP','Integer Vitae Incorporated','tellus. Nunc lectus pede, ultrices','30311','15');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('71','Lisinopril','Magna A Neque Corporation','vitae, sodales','49431','7');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('72','Methylprednisolone','Sed Ltd','Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare,','36343','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('73','Ciprofloxacin HCl','Proin Corporation','penatibus et magnis dis parturient montes, nascetur','59864','8');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('74','Niaspan','Lorem Ltd','nec','82930','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('75','Cymbalta','Magna Associates','felis orci, adipiscing non, luctus sit amet, faucibus ut,','85873','14');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('76','Diazepam','Morbi Metus Vivamus Ltd','eget magna. Suspendisse','99167','5');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('77','Atenolol','Convallis Ante Limited','hendrerit neque. In ornare sagittis felis. Donec','50014','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('78','Lantus Solostar','Libero Mauris LLP','a felis ullamcorper','97530','9');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('79','Glipizide','At Egestas Consulting','nulla. Donec','12398','19');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('80','Lisinopril/Hydrochlorothiazide','Egestas Hendrerit Ltd','gravida non, sollicitudin a, malesuada','9921','19');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('81','Bystolic','Orci Ut Semper Foundation','velit. Cras lorem lorem, luctus ut, pellentesque','15656','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('82','Synthroid','Tristique Pellentesque Company','erat neque non quam. Pellentesque habitant','95119','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('83','Cheratussin AC','Urna Inc.','convallis dolor. Quisque tincidunt','59881','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('84','Lorazepam','Pellentesque Inc.','sem egestas blandit. Nam nulla magna, malesuada vel,','35634','6');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('85','Nuvaring','Et Malesuada PC','dolor. Fusce feugiat. Lorem ipsum dolor sit','16429','16');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('86','Potassium Chloride','Pharetra Sed Hendrerit LLP','pretium et, rutrum non, hendrerit id, ante. Nunc mauris','27559','12');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('87','Nuvaring','Sed Dui Consulting','Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam','40733','10');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('88','Nexium','Adipiscing Mauris Molestie LLP','sed dictum eleifend, nunc risus varius','13677','12');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('89','Enalapril Maleate','Eget Industries','ante. Nunc mauris sapien, cursus in, hendrerit','14842','20');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('90','Triamcinolone Acetonide','Consequat Dolor Vitae Foundation','ligula. Nullam feugiat placerat','5815','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('91','Risperidone','Dolor Fusce Feugiat Ltd','pellentesque. Sed dictum. Proin eget','22557','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('92','Zetia','Elit Pretium PC','iaculis','26458','13');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('93','Hydrochlorothiazide','Commodo Auctor Velit Incorporated','consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque,','7552','14');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('94','Diazepam','Massa Mauris Institute','arcu. Morbi','33861','15');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('95','Amoxicillin Trihydrate/Potassium Clavulanate','Blandit At Nisi Limited','Suspendisse sagittis. Nullam','8223','7');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('96','Zolpidem Tartrate','Dapibus PC','rutrum, justo. Praesent luctus.','79356','18');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('97','Furosemide','Congue A Aliquet Institute','neque. Nullam nisl. Maecenas malesuada fringilla est.','27658','11');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('98','Lorazepam','Neque Venenatis Lacus Inc.','magna. Duis dignissim tempor','69730','17');
Insert into IMPLEMENTO (ID,NOMBRE,MARCA,DESCRIPCION,COSTO,CANTIDAD) values ('99','Glipizide','Velit Incorporated','bibendum','73645','10');


REM INSERTING into TRATAMIENTO
SET DEFINE OFF;

Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('1','39611','0,5','luctus. Curabitur egestas nunc');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('2','12970','0,23','adipiscing non, luctus');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('3','12691','0,73','rhoncus id, mollis nec,');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('4','38047','0,79','enim. Nunc ut');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('5','9609','0,66','fermentum arcu.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('6','15382','0,22','fringilla euismod');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('7','29621','0,37','magnis');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('8','31789','0,42','vel lectus. Cum sociis');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('9','34625','0,75','vitae,');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('10','25479','0,52','ante ipsum');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('11','2612','0,42','Suspendisse commodo');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('12','7576','0,76','placerat, augue.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('13','12783','0,65','euismod enim. Etiam gravida');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('14','27701','0,21','molestie dapibus ligula. Aliquam erat');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('15','8511','0,79','non dui nec urna');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('16','27223','0,48','aliquet, sem ut cursus');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('17','12679','0,35','sagittis. Duis');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('18','26872','0,58','turpis. In');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('19','31049','0,41','dictum');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('20','14957','0,66','eros. Nam consequat');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('21','22717','0,78','magna.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('22','14332','0,39','aptent taciti sociosqu');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('23','4733','0,79','et ipsum');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('24','7293','0,45','vel est tempor bibendum.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('25','36287','0,59','metus. Aenean');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('26','7592','0,31','orci');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('27','27666','0,55','elit, pellentesque');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('28','26323','0,46','nec, cursus a, enim. Suspendisse');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('29','36108','0,48','enim nec');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('30','24888','0,37','Etiam ligula tortor,');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('31','26312','0,78','urna, nec');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('32','19678','0,68','Donec luctus aliquet');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('33','21712','0,66','metus');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('34','30328','0,51','pellentesque. Sed dictum.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('35','10969','0,55','Curabitur consequat, lectus');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('36','26842','0,39','commodo at, libero.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('37','5336','0,39','vitae risus. Duis a');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('38','26535','0,33','tempor');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('39','2530','0,23','Vivamus');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('40','29411','0,74','rutrum.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('41','22142','0,4','tellus. Nunc lectus pede,');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('42','36777','0,63','interdum enim non nisi. Aenean');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('43','13118','0,67','eu elit.');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('44','9291','0,27','sodales purus, in molestie');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('45','17879','0,8','bibendum. Donec felis');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('46','22958','0,53','Mauris magna. Duis');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('47','23231','0,71','morbi tristique senectus et');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('48','12635','0,73','Donec felis orci,');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('49','38749','0,28','semper pretium neque. Morbi quis');
Insert into TRATAMIENTO (ID,COSTO,PORCE_GANAN_MEDICO,DESCRIPCION) values ('50','9662','0,35','a, scelerisque sed, sapien.');


REM INSERTING into MEDICO
SET DEFINE OFF;

Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('12243156','Cally',to_date('25/08/60','DD/MM/RR'),'519-3047 Enim, St','16091202-8644','V6191201','8824');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('13443537','Venus',to_date('17/06/64','DD/MM/RR'),'2180 Diam St','16940714-0830','V6490615','3429');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('19534932','Kelsie',to_date('20/08/88','DD/MM/RR'),'Ap #495-3802 Nibh Avenue','16011015-5538','V6611026','8595');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('17586616','Arden',to_date('23/08/86','DD/MM/RR'),'Ap #732-7102 Felis Av','16551208-6041','V6191225','5199');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('5732941','Candice',to_date('12/02/65','DD/MM/RR'),'751-5185 Sollicitudin Ave','16720814-8747','V6801107','6057');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('17853792','Zane',to_date('17/12/74','DD/MM/RR'),'PO Box 698, 5174 At Road','16401215-3567','V6900827','6070');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('12581719','Brenda',to_date('11/11/86','DD/MM/RR'),'Ap #729-5337 Lobortis Rd','16701009-1697','V6491202','7192');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('9445503','Xerxes',to_date('28/11/74','DD/MM/RR'),'377-8012 Sagittis Road','16731226-3218','E6200301','7129');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('5754529','Leandra',to_date('31/08/67','DD/MM/RR'),'Ap #305-8837 Ut Rd','16020620-0131','E6010409','4152');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('11455303','Jasper',to_date('23/03/69','DD/MM/RR'),'Ap #813-7458 Cursus St','16251101-0098','E6550718','2631');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('12953301','Samuel',to_date('24/10/87','DD/MM/RR'),'PO Box 739, 3608 Ac St','16380705-5094','E6831011','2045');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('15008907','Echo',to_date('23/03/74','DD/MM/RR'),'248-8301 Sollicitudin Rd','16340713-0339','P6230110','2173');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('15133763','Eagan',to_date('20/05/86','DD/MM/RR'),'1399 Erat St','16351123-0124','P6250429','9375');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('9373697','Rooney',to_date('20/05/71','DD/MM/RR'),'Ap #432-9217 Lectus Rd','16411008-9077','P6460525','8401');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('9231387','Casey',to_date('29/06/73','DD/MM/RR'),'935-3683 Elit, Av','16390928-7900','G6640602','4165');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('15877111','Cameran',to_date('31/03/79','DD/MM/RR'),'478-5289 Vulputate Ave','16940624-4708','G6220123','2807');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('19586084','Colorado',to_date('06/08/88','DD/MM/RR'),'PO Box 864, 8876 Est Avenue','16100725-9318','G6570211','4067');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('16506036','Vernon',to_date('02/10/69','DD/MM/RR'),'Ap #277-1886 Nisl Rd','16740217-3202','G6260417','5178');
Insert into MEDICO (CI,NOMBRE,FECHA_NAC,DIRECCION,TELEFONO,RIF,NUM_COLEGIO) values ('13023488','Lucas',to_date('12/06/65','DD/MM/RR'),'151-9741 Vulputate, St','16900524-8134','J6971114','2943');
